import './Qrcode.css';
import { useState } from 'react';

const Qrcode = () => {
  const [img, setImg] = useState('');
  const [loading, setLoading] = useState(false);
  const [qrData, setQrData] = useState('ini');
  const [qrSize, setQrSize] = useState('150');

  async function generateQR() {
    setLoading(true);
    try {
      const url = `https://api.qrserver.com/v1/create-qr-code/?size=${qrSize}x${qrSize}&data=${encodeURIComponent(qrData)}`;
      setImg(url);
    } catch (error) {
      console.error('Error generating QR code:', error);
    } finally {
      setLoading(false);
    }
  }

  function downloadQR() {
    const link = document.createElement('a');
    link.href = img;
    link.download = 'qr-code.png';
    link.click();
  }

  return (
    <>
      <div className="app-container">
        <h1>QR CODE GENERATOR</h1>
        {loading && <p>please wait...</p>}
        {img && <img src={img} className="qr-img" alt="QR code generated by the QR code generator" />}
        <div>
          <label htmlFor="dataInput" className="input-label">
            Data for QR code
          </label>
          <input
            type="text"
            value={qrData}
            id="dataInput"
            placeholder="Enter data for QR code"
            onChange={(e) => setQrData(e.target.value)}
          />
          <label htmlFor="sizeInput" className="input-label">
            Image size (e.g., 150)
          </label>
          <input
            type="text"
            value={qrSize}
            onChange={(e) => setQrSize(e.target.value)}
            id="sizeInput"
            placeholder="Enter image size"
          />
          <div>
            <button className="generate-btn" onClick={generateQR}>
              Generate QR code
            </button>
            <button className="download-btn" onClick={downloadQR}>
              Download QR code
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Qrcode;